finished
Adamozo/advent_of_code pull request #17
Opened 2022-05-14 08:46 UTC by Adamozo

https://adventofcode.com/2020/day/11

Zadanie zrobiłem w dwóch wersjach i zgodnie z ostatnią rozmową jedna to używanie raz za alokowanych plansz a druga to tworzenie nowej za każdym razem. Dla planszy podanej w zadaniu otrzymałem takie wyniki:
![obraz](https://user-images.githubusercontent.com/68241874/168418436-a1204b73-aa28-4ed9-adbd-e2263870e584.png)

2022-05-14 13:06 UTC, pdodev requested changes
Na razie nie robię dalszych komentarzy, ponieważ wymagane zmiany są dosyć duże.

2022-05-14 13:06 UTC, pdodev commented on src/ex11.rs
> +                && board[(row + r) as usize][(col + c) as usize] == LocationState::Occupied
Obie te metody `is_any_adjacet_seats_occupied` oraz `change_to_free_needed` mają bardzo dużo powtarzającej się (i do tego skomplikowanej) logiki.  To się da 'uwspólnić' ... Zwróć uwagę na tę część treści zadania:
```
If a seat is empty (L) and there are no occupied seats adjacent to it, the seat becomes occupied.
If a seat is occupied (#) and four or more seats adjacent to it are also occupied, the seat becomes empty.
```
To czy dane siedzenie stanie się zajęte, czy zostanie zwolnione zależy od **ilości** zajętych miejsc w sąsiedztwie, zatem tą częścią wspólną logiki obu tych metod jest metoda np. o takiej nazwie:
```
fn num_occupied_adjacent_cells(&self, row: usize, col: usize) -> u8 
{
   ...
}
```
To w update_board(2) powinieneś mieć _właściwą_ logikę:
```
 match self.grid[row][col] {
    EmptySeat if self.num_occupied_adjacent_cells(row, col) == 0 => {
        ...
    }
    OccupiedSeat if self.num_occupied_adjacent_cells(row, col) >= 4 => {
       ...
    }
    ...
}
```

2022-05-16 08:41 UTC, pdodev requested changes

2022-05-16 08:41 UTC, pdodev commented on src/ex11.rs
> +        .fold(0, |acc, _x| acc + 1)
zamiast `.fold` można tutaj użyć: `.count() as u8`

2022-05-16 08:41 UTC, pdodev commented on src/ex11.rs
> +            }
```rust
match base_board[row][col] {
    Empty if occupied == 0 => {
        result_board[row][col] = Occupied;
        was_any_seat_changed = true;
        occupied_seats_num += 1;
    },
    Occupied if occupied >= 4 => {
        result_board[row][col] = Empty;
        was_any_seat_changed = true;
    },
    Occupied => {
        occupied_seats_num += 1;
    },
    _ => {},
}
```

2022-05-16 08:41 UTC, pdodev commented on src/ex11.rs
> +            }
Patrz uwaga do: update_board2

2022-05-17 20:41 UTC, Adamozo commented
Wprowadziłem zmiany jedna nie rozumiem fragmentu:

Empty if occupied == 0 => {
                    result_board[row][col] = Occupied;
                    was_any_seat_changed = true;
                    occupied_seats_num += 1;
                }

Nie jestem w stanie wpaść na to dlaczego if po enumeratorze działa i co właściwie oznacza ten fragment

2022-05-19 22:09 UTC, merged