Ex15
Adamozo/advent_of_code pull request #20
Opened 2022-05-22 12:24 UTC by Adamozo

https://adventofcode.com/2020/day/15

2022-05-23 06:57 UTC, pdodev requested changes
Zrób drugą wersję opartą na HashMapie i dodaj benchmark, ale nie dla 2020 iteracji tylko np. 100_000 (wtedy różnica powinna być bardziej widoczna).

Możesz pokusić się o zaimplementowanie trzeciej wersji ... :-), opartej na Vec (!!! :-)), **ale** który
**działa jak mapa** (key => wartość indeksu) ; chodzi o uzyskanie szybkiego wyszukiwania:
```rust
spoken_number2turn: Vec<u32> = vec![0; ...];
```

2022-05-23 06:57 UTC, pdodev commented on src/ex15.rs
> +        turns.remove(turns.len() - 1);
let start_value = turns.last().unwrap().1;  // turns.last() <=> turns[turns.len() - 1] 
turns.pop();   // <=> turns.remove(turns.len() - 1);

2022-05-23 06:57 UTC, pdodev commented on src/ex15.rs
> +            match turns.iter().position(|&(_, num)| num == new_num) {
To wygląda podejrzanie: **szukanie** w **Vec** w **pętli**. 
W tym wypadku HashMap-a powinna być mniej kosztowna (zresztą zobacz co jest elementem w twoim Vec-u - para wartości ...)

2022-05-26 23:16 UTC, Adamozo commented
Dodałem wersję z hash mapą i okazała się być dużo szybsza niż ta z vektorem. Dodałem też wersję z zainicjalizowanym wcześniej vektorek i okazała się być dwa rzędy wielkości wolniejsza niż hash mapa stąd wydaje mi się, że mogłem coś źle zaimplementować ale nie jestem w stanie zlokalizować potencjalnego błędu. 

![obraz](https://user-images.githubusercontent.com/68241874/170594413-c70ac801-2975-4997-bff2-6308a5ce904e.png)

2022-05-27 04:51 UTC, pdodev commented
Popatrz na ten kod (ex15c.rs), dodałem kilka "liczników" - to sporo wyjaśnia:

```rust
 fn solution(_s: &str) -> anyhow::Result<<Self as DaySolver>::Output> {
        let mut turns: Vec<u32> = vec![0; SIZE];
        let start_index = insert_init_values(&mut turns, _s)?;

        let mut i1 = 0;
        let mut i2 = 0;
        let mut i3 = 0;

        let res = (start_index + 1..SIZE).fold(turns[start_index], |new_num, turn_num| match turns
            .iter()
            .rev()
            .map(|e| {
                i1 += 1;
                e
            })
            .skip(turns.len() - turn_num + 1)
            .map(|e| {
                i2 += 1;
                e
            })
            .position(|&num| {
                i3 += 1;
                num == new_num
            }) {
            None => {
                turns[turn_num - 1] = new_num;
                0
            },
            Some(index) => {
                let next_value = (index + 1) as u32;
                turns[turn_num - 1] = new_num;
                next_value
            },
        });

        println!("i1={}", i1);
        println!("i2={}", i2);
        println!("i3={}", i3);

        Ok(res)
    }
```
```sh
i1=1734258242
i2=1029375538
i3=1029375538
```

2022-05-27 04:58 UTC, pdodev commented
Na moim komputerze twoje 3 wersje dają takie czasy:
```sh
{ "day": "day_15", "label": "vector with tuple", "input": "File", "elapsed_time": "    47.330ms", "output": "340" }
{ "day": "day_15", "label": "hash map", "input": "File", "elapsed_time": "     2.929ms", "output": "340" }
{ "day": "day_15", "label": "vector with capacity", "input": "File", "elapsed_time": "   251.913ms", "output": "340" }
```
Chodziło o **taką** mapę na wektorze (hint: spoken_number2turn), aby móc uzyskać taki czasy:
```sh
{ "day": "day_15", "label": "basic", "input": "String", "elapsed_time": "   311.144µs", "output": "340" }
```

2022-05-27 15:41 UTC, Adamozo commented
Zmieniłem implementację wersji c tak aby indeks w wektorze oznaczał obliczoną wartość. W komórce wektora umieściłem turę ostatniego pojawienia. Rzeczywiście udało się znacznie zbić czas.

2022-05-27 19:06 UTC, pdodev approved these changes

2022-05-28 09:25 UTC, merged