Ex16 push
Adamozo/advent_of_code pull request #21
Opened 2022-05-28 09:29 UTC by Adamozo

https://adventofcode.com/2020/day/16

2022-05-28 11:11 UTC, pdodev requested changes

2022-05-28 11:11 UTC, pdodev commented on src/ex16.rs
> +}
Wydaje mi się, że te tego kodu nie trzeba dawać do oddzielnej metody.
Pozbędziesz się też collect-a w collect-ie.

2022-05-28 11:11 UTC, pdodev commented on src/ex16.rs
> +    fn solution(_s: &str) -> anyhow::Result<<Self as DaySolver>::Output> {
```rust
<Self as DaySolver>::Output  -> Self::Output
```

2022-05-28 11:11 UTC, pdodev commented on src/ex16.rs
> +            .collect();
spróbuj bez collect-a (input_sections[1] i tak nie używasz; hint: mut input_sections i potem odpowiednio input_sections.next())

2022-05-28 12:55 UTC, Adamozo commented on src/ex16.rs
> +            .collect();
Nie za bardzo wiem jak mógłbym wykorzystać mut input_sections dlatego pozbyłem się collectów korzystając z folda

2022-05-28 13:12 UTC, pdodev commented on src/ex16.rs
> +            .collect();
Np.
```rust
let (classes_section, nearby_tickets_section) = {
            let mut sections = s.split(INPUT_SECTION_DELIMETER);

            (sections.next().unwrap(), {
                sections.next(); // skip "your ticket section"
                sections.next().unwrap()
            })
        };
```

2022-05-29 05:22 UTC, pdodev approved these changes

2022-07-07 12:45 UTC, closed without merging