Ex4
Adamozo/advent_of_code pull request #9
Opened 2022-03-31 16:21 UTC by Adamozo

W rozwiązaniu skorzystałem z możliwości nie sprawdzania opcjonalnego pola cid. Tym razem założyłem, że dane są poprawne, kompletne i mają zachowaną strukturę jak w zadaniu. https://adventofcode.com/2020/day/4

2022-04-01 13:25 UTC, pdodev requested changes
- zmiany w ex2.rs logicznie nie należą do tego pull-a 
- zaimplementuj to bez wczytywania wszystkiego do pamięci

2022-04-01 13:25 UTC, pdodev commented on src/ex4.rs
> +fn count_valid_passports(passports: &[String]) -> usize {
Taki sposób implementacji sprawdzania, czy wszystkie wymagane pola występują w rekordzie jest bardzo kosztowny ->
is_field_interesting + count >=7

2022-04-01 13:25 UTC, pdodev commented on src/ex4.rs
> +fn load_data<P>(path: P) -> io::Result<Vec<String>>
Jeżeli już chcesz ładować cały plik do pamięci, to dużo prościej jest użyć funkcję std::fs::read_to_string + .split("\n\n").

2022-04-01 13:25 UTC, pdodev commented on src/ex4.rs
> +    for line in read_lines(path)? {
Czy rzeczywiście musisz zbierać w passports całą zawartość danej linii wejściowej ?

2022-04-01 16:50 UTC, pdodev commented
Zwróć uwagę:
- ile masz stanów do sprawdzenia (dla jednego rekordu)
- wynikiem ma być pojedyncza liczba

2022-04-15 20:11 UTC, Adamozo commented
Miałem problemy z przepisaniem iteratora używanego do wczytywania z pliku po liniach tak aby działało to w miejscu(na jednym stringu), dlatego też przesłane przeze mnie zmiany jeszcze tego nie zawierają.

2022-04-16 10:55 UTC, pdodev commented
W pliku data_files/ex4.txt zmień kolejność rekordów i daj jako ostatni **poprawny** rekord, a potem
uruchom funkcję testującą **test_ex4_count_valid_passports** i zobacz co się stanie.

2022-04-16 11:00 UTC, pdodev commented
Spróbuj to zaimplementować **bez** tablicy: **mapper:[bool; 7]** .
Podpowiedź:

```
.map(|key| match key {
    "byr" => 1,
    "iyr" => 2,
    "eyr" => 4,
    "hgt" => 8,
    "hcl" => 16,
    "ecl" => 32,
    "pid" => 64,
    "cid" => 0,
    _ => unreachable!(),
})
```

2022-04-22 21:46 UTC, closed without merging